'use strict';
const assert=require('node:assert/strict');
const {TutorialGame}=require('./js/engine/tutorial');
const {Game}=require('./js/engine/game');
const g=new TutorialGame();
assert.equal(g.units.length,2);assert.equal(g.cities.length,2);
assert.equal(g.inMap(8,2),false);assert.equal(g.inMap(7,4),true);
assert.equal(g.tile(8,2),null);assert.equal(g.checkVictory(),null);
assert.throws(()=>g.serialize(),/教程/);
assert.equal(g.moveUnit(g.trainee,2,2),false);g.endTurn();assert.equal(g.turn,0);
g.lesson=2;
assert(g.moveUnit(g.trainee,1,1));assert.equal(g.lesson,3);assert(g.trainee.attacked);
assert(g.undoMove(g.trainee));assert.equal(g.lesson,4);assert(!g.trainee.moved&&!g.trainee.attacked);
assert(g.moveUnit(g.trainee,2,2));assert.equal(g.lesson,5);assert(!g.trainee.attacked);
assert(g.attack(g.trainee,g.target).killed);assert.equal(g.lesson,6);assert(!g.canUndoMove(g.trainee));
g.endTurn();assert.equal(g.lesson,7);assert.equal(g.gold.axis,205);
assert(g.moveUnit(g.trainee,4,2));assert.equal(g.lesson,8);assert(g.trainee.attacked);
assert.equal(g.cityByKey['training-town'].owner,'axis');assert.equal(g.factionIncome('axis'),40);
const recruit=g.recruit('training-base','de:infantry:0');assert(recruit);assert(recruit.moved&&recruit.attacked);
g.endTurn();assert.equal(g.lesson,10);assert.equal(g.gold.axis,185);assert(!recruit.moved&&!recruit.attacked);
assert.equal(g.pendingEvents.length,0);assert.equal(g.units.length,2);
assert.equal(new TutorialGame().lesson,0);
const campaign=new Game('axis');assert.equal(campaign.cities.length,436);assert.equal(campaign.units.length,1010);
assert(Game.deserialize(campaign.serialize()).units.length===1010);
console.log('Tutorial: bounded map, guided actions, normal combat, capture, recruitment, income, turn reset, no save writes/events and unaffected campaign passed.');
