'use strict';
const assert=require('node:assert/strict');
const {Game,hexDist,key}=require('./js/engine/game');
const g=new Game('axis','normal',{initialFleet:false});g.units=[];g.gold.axis=10000;
const berlin=g.cityByKey.berlin,baseKey='berlin';
assert(g.airfields.length>60);assert(g.airfields.every(c=>!c.demilitarized));
for(const k of ['berlin','london','paris','moscow','rome'])assert(g.airfields.includes(g.cityByKey[k]));
assert(!g.rosterFor(berlin).some(o=>o.eq.cls==='air'));
assert.equal(g.recruit(baseKey,'de:air:0'),null,'ordinary recruit cannot produce aircraft');
const noAirport=g.cities.find(c=>c.owner==='axis'&&!g.airfields.includes(c));
assert.equal(g.recruitAir(noAirport.k,'de:air:0'),null);
assert.equal(g.recruitAir('london','uk:air:0'),null,'enemy airfield');
assert.equal(g.recruitAir(baseKey,'uk:air:0'),null,'foreign equipment');
assert.equal(g.recruitAir(baseKey,'de:inf:0'),null,'ground equipment');
const ground=g.spawnUnit('de','de:inf:0',berlin.x,berlin.y,{});
const money=g.gold.axis,air=g.recruitAir(baseKey,'de:air:0');
assert(air);assert.equal(money-g.gold.axis,air.eq.cost);assert(air.moved&&air.attacked);assert.equal(g.unitAt(berlin.x,berlin.y),ground);
assert(g.recruitAir(baseKey,'de:air:0'),'multiple formations share an airport');
g.gold.axis=0;assert.equal(g.recruitAir(baseKey,'de:air:0'),null);g.gold.axis=10000;
g.startTurnFor('axis');assert.equal(air.airbase,baseKey);
const radius=g.airRadius(air),inRange=g.neighbors(berlin.x,berlin.y).find(p=>g.landPassable(...p));
const enemy=g.spawnUnit('uk','uk:inf:0',...inRange,{});
const outside=g.spawnUnit('uk','uk:inf:0',g.cityByKey.london.x,g.cityByKey.london.y,{});
assert(g.targetsOf(air).includes(enemy));assert(!g.targetsOf(air).includes(outside));
assert(g.canStrikeFrom(air,air.c,air.r,{...enemy,c:air.c+radius,r:air.r}),'range boundary included');
assert(!g.canStrikeFrom(air,air.c,air.r,{...enemy,c:air.c+radius+1,r:air.r}),'outside range rejected');
assert(!g.moveUnit(air,...inRange),'no field landing/capture');
const owner=g.cityByKey.berlin.owner;
assert(g.attack(air,enemy));assert.equal(air.airbase,baseKey);assert.equal(air.c,berlin.x);assert.equal(air.r,berlin.y);assert.equal(berlin.owner,owner);assert.equal(g.attack(air,enemy),null,'one sortie per turn');
g.startTurnFor('axis');
const next=g.airfields.find(c=>c.owner==='axis'&&c!==berlin&&hexDist(air.c,air.r,c.x,c.y)<=radius);assert(next);
assert(g.moveRange(air).cost.has(key(next.x,next.y)));
assert(g.rebaseAir(air,next.k));assert(air.moved&&air.attacked);assert.equal(air.airbase,next.k);assert(!g.rebaseAir(air,baseKey));
g.startTurnFor('axis');assert(!g.rebaseAir(air,'london'));
const far=g.airfields.find(c=>c.owner==='axis'&&hexDist(air.c,air.r,c.x,c.y)>radius);if(far)assert(!g.rebaseAir(air,far.k));
const saved=g.serialize(),restored=Game.deserialize(saved);assert.equal(restored.units.find(u=>u.id===air.id).airbase,next.k);
const broken=JSON.parse(saved);broken.units.find(u=>u.id===air.id).airbase='london';assert.throws(()=>Game.deserialize(JSON.stringify(broken)),/空军机场/);
const old=JSON.parse(saved);old.v=6;const oldAir=old.units.find(u=>u.id===air.id);delete oldAir.airbase;oldAir.c=55;oldAir.r=60;
const migrated=Game.deserialize(JSON.stringify(old)),m=migrated.units.find(u=>u.id===air.id);assert(migrated.airBase(m));assert.equal(m.hp,air.hp);assert.equal(m.eqKey,air.eqKey);
const ship=g.spawnUnit('uk','uk:dd:0',0,1,{});assert(g.canCounter(ship,air),'naval AA responds to incoming sortie, not distant base');
const enemyBase=g.airfields.find(c=>c.owner==='west');const enemyAir=g.spawnUnit('uk','uk:air:0',enemyBase.x,enemyBase.y,{});assert(g.canCounter(enemyAir,air));
g.captureCity(next,'west');assert(!g.units.includes(air),'aircraft lost with captured base');
const ai=new Game('axis','normal',{initialFleet:false});ai.units=[];const london=ai.cityByKey.london;const aiAir=ai.spawnUnit('uk','uk:air:0',london.x,london.y,{});
const target=ai.spawnUnit('de','de:inf:0',...ai.landNeighbors(london.x,london.y)[0],{});const hp=target.hp;ai.aiAir('west',[],true);assert(target.hp<hp,'AI sorties');assert.equal(aiAir.airbase,'london');
console.log('Airfields: recruitment isolation, shared base, radius, sorties, transfers, capture, saves and AI passed.');

const early=new Game('west','normal',{initialFleet:false});early.units=[];early.gold.west=10000;
assert.equal(early.recruitAir('london','uk:air:0'),null,'1942 model locked in 1939');
const basic=early.recruitAir('london',early.airRoster(early.cityByKey.london).find(o=>o.eq.airRole==='fighter').eqKey);assert(basic&&basic.ct==='uk','1939 national fighter keeps allegiance');
early.turn=28;assert(early.recruitAir('london','uk:air:0'),'1942 unlock');
const occupied=new Game('axis','normal',{initialFleet:false});occupied.units=[];occupied.gold.axis=10000;
occupied.captureCity(occupied.cityByKey.london,'axis');const occupationAir=occupied.recruitAir('london','de:air:0');assert(occupationAir&&occupationAir.ct==='de'&&occupationAir.airbase==='london');
const original=early.cityByKey.berlin.owner;assert.equal(early.captureCity(early.cityByKey.berlin,'west',basic),false);assert.equal(early.cityByKey.berlin.owner,original);
console.log('Airfields: early generic aircraft, year unlocks and occupied-airport allegiance passed.');
