'use strict';
const assert=require('node:assert/strict');
const {Game}=require('./js/engine/game');
const {AIR,ECONOMY}=require('./js/data/load-node');
for(const entries of Object.values(AIR.equipment))for(const eq of entries)assert.equal(eq.cost,Math.round(AIR.roles[eq.airRole].cost*(1+.1*eq.tier)));
let g=new Game('axis','normal',{initialFleet:false});g.units=[];g.gold.axis=10000;
const city=g.cities.find(ci=>ci.owner==='axis'&&!g.airfields.includes(ci)&&!ci.demilitarized);
const coast=g.cities.find(ci=>ci.owner==='axis'&&!ci.demilitarized&&!g.harbors.some(h=>h.cityKey===ci.k)&&g.harborSites(ci).length);
assert(city&&coast);
assert(!g.startConstruction('london','factory'));
assert(!g.startConstruction(city.k,'unknown'));
assert(!g.startConstruction('berlin','airfield'));
const site=g.harborSites(coast)[0];
assert(!g.startConstruction(coast.k,'harbor',[coast.x,coast.y]));
assert(!g.startConstruction(coast.k,'harbor'));
g.gold.axis=0;assert(!g.startConstruction(city.k,'factory'));g.gold.axis=10000;
const before=g.gold.axis,income=g.cityIncome(city);
assert(g.startConstruction(city.k,'factory'));
assert(g.startConstruction(city.k,'airfield'));
assert(g.startConstruction(coast.k,'harbor',site));
assert.equal(g.gold.axis,before-450);
assert(!g.startConstruction(city.k,'factory'));assert.equal(g.gold.axis,before-450);
assert(!g.harborSites(coast).some(p=>p[0]===site[0]&&p[1]===site[1]));
assert(!g.recruitAir(city.k,'de:air:0'));
function endRound(){g.aiTurn=()=>[];g.endTurn();}
endRound();assert(!g.airfields.includes(city));
const cityKey=city.k,coastKey=coast.k;
g=Game.deserialize(g.serialize());
assert.equal(g.construction.find(p=>p.kind==='airfield').remaining,1);
endRound();assert(g.airfields.includes(g.cityByKey[cityKey]));
assert(!g.cityByKey[cityKey].factory);assert(!g.harbors.some(h=>h.cityKey===coastKey));
const plane=g.recruitAir(cityKey,g.airRoster(g.cityByKey[cityKey]).find(o=>!o.locked).eqKey);assert(plane);
g=Game.deserialize(g.serialize());assert.equal(g.airBase(g.units.find(u=>u.id===plane.id)).k,cityKey);
const blocker=g.spawnUnit('uk','uk:dd:0',...site,{});endRound();
assert(g.cityByKey[cityKey].factory);assert.equal(g.cityIncome(g.cityByKey[cityKey]),income);
assert(!g.harbors.some(h=>h.cityKey===coastKey));assert.equal(g.construction[0].remaining,1);
g.killUnit(blocker);endRound();assert.equal(g.construction.length,0);
assert(g.harbors.some(h=>h.cityKey===coastKey&&h.c===site[0]&&h.r===site[1]));
assert(g.recruitNaval(coastKey,g.navalRoster(g.cityByKey[coastKey]).find(o=>!o.locked).eqKey));
g=Game.deserialize(g.serialize());assert(g.cityByKey[cityKey].factory);assert(g.airfields.includes(g.cityByKey[cityKey]));assert(g.harbors.some(h=>h.cityKey===coastKey));
const inherited=g.cities.find(c=>c.owner==='axis'&&!c.cap&&!c.factory&&!c.demilitarized);
assert(g.startConstruction(inherited.k,'factory'));g.captureCity(inherited,'west');
for(let i=0;i<3;i++)endRound();assert(inherited.factory);assert.equal(inherited.owner,'west');
const inland=g.cities.find(c=>!g.neighbors(c.x,c.y).some(p=>g.ocean(...p))&&c.owner==='axis');assert(g.constructionError(inland.k,'harbor'));
const dm=g.cities.find(c=>c.demilitarized);dm.owner='axis';assert(!g.startConstruction(dm.k,'airfield'));
const old=JSON.parse(new Game('axis','normal',{initialFleet:false}).serialize());old.v=8;delete old.facilities;delete old.construction;
const legacy=Game.deserialize(JSON.stringify(old));assert(legacy.airfields.length>60);assert.equal(legacy.construction.length,0);
const bad=JSON.parse(g.serialize());bad.construction=[{cityKey:'bad',kind:'factory',remaining:1}];assert.throws(()=>Game.deserialize(JSON.stringify(bad)),/建设数据/);
console.log('PASS construction: pricing, costs, legality, turn timing, capture, blocked harbor, recruitment, saves and legacy migration');
// Initial industry follows the same major-city tier as airfields and never leaks into loaded saves.
const opening=new Game('axis');const factories=opening.cities.filter(c=>c.factory);
assert.equal(factories.length,93);assert.deepEqual(factories.map(c=>c.k),opening.airfields.map(c=>c.k));assert.deepEqual(opening.gold,require('./js/data/load-node').START_GOLD);
for(const k of ['berlin','hamburg','essen','london','manch','paris','lyon','moscow','leningrad','rome','milan'])assert(opening.cityByKey[k].factory,k);
assert.equal(opening.construction.length,0);assert(!factories.some(c=>c.demilitarized));
opening.units=[];assert(opening.recruitFactory('berlin','de:gun_gun:0'));assert(!opening.startConstruction('berlin','factory'));
assert.equal(Game.deserialize(opening.serialize()).cities.filter(c=>c.factory).length,93);
const prior=new Game('axis','normal',{initialFactories:false});prior.gold.axis=1000;assert(prior.startConstruction('berlin','factory'));prior.advanceConstruction();
const priorLoaded=Game.deserialize(prior.serialize());assert(!priorLoaded.cityByKey.berlin.factory);assert.equal(priorLoaded.construction[0].remaining,2);
const ancient=JSON.parse(prior.serialize());delete ancient.facilities;delete ancient.construction;ancient.v=8;assert.equal(Game.deserialize(JSON.stringify(ancient)).cities.filter(c=>c.factory).length,0);
console.log('Initial factories: 93 major cities, ready production, unchanged gold, saved factories and old in-progress construction passed');
